### ISSUE TITLE
couldn't find my botnick some_nick in configuration of Topclient

### ISSUE THREAD

**Issue by scriptzteam** [dupe/TopClient-save-nfo-sfv-top#1]
couldn't find my botnick some_nick in configuration of Topclient

**Comment by dupe** [comment]
set topclient.conf 

botnick  = name bot eggdrop

**Comment by scriptzteam** [comment]
hmm but when i want start that script TopClient.tcl it always says that "couldn't find my botnick some_nick in configuration of Topclient" so how i set it ?

**Comment by dupe** [comment]
fake it configures
topclient.conf correctly for it to work

set name  eggdrop

put the name of your eggdrop in part topclient.conf ligne 

set top_config(bot_dest) "all"

set name bot topsite 

and the name of bot that announces information on irc

search ligne 

# proc_annonce_top

to conf bot name topsite

**Comment by scriptzteam** [comment]
my config file -- http://pastebin.com/ZyHMRDCg

##Config LOGIN 
set topsite(test_user) ""
set topsite(test_pass) ""
set topsite(test_host) ""
set topsite(test_port) ""
##Config LFTP
set topsite(***_LFTP_CONFIG) "set net:timeout 5s"
##Config Donwload
set topsite(test_DL_SFV) "1"
set topsite(test_DL_NFO) "1"
set topsite(test_DL_M3U) "1"
set topsite(test_DL_JPG) "1"
set topsite(test_DL_CUE) "1"
set topsite(test_DL_SAMPLE) "1"
set topsite(test_DL_COVER) "1"
set topsite(test_DL_MP3) "1"
##Config CMD
set topsite(test_SITEPRE) "1"
set topsite(test_SITEPRE_TO_ADDPRE) "1"
set topsite(test_SITEPRE_TO_INFO) "1"
set topsite(test_NEWDIR) "1"
set topsite(test_MP3INFO) "1"
set topsite(test_FILEINFO) "1"
set topsite(test_ADDINFO) "1"
set topsite(test_ADDGINFO) "1"
set topsite(test_ADDURL) "1"
##Config Dynamic Section

set topsite(test_SECTION_1) "/ENGLISH/0DAY/0528/"
set topsite(test_SECTION_1_TODAY) "/ENGLISH/0DAY/0528/"
set topsite(test_SECTION_2) "EBOOK"
set topsite(test_SECTION_2_TODAY) "EBOOK-Month"
set topsite(test_SECTION_3) "FLAC"
set topsite(test_SECTION_3_TODAY) "FLAC-today"
set topsite(test_SECTION_4) "MP3"
set topsite(test_SECTION_4_TODAY) "MP3-today"
set topsite(test_SECTION_5) "MViD"
set topsite(test_SECTION_5_TODAY) "MViD-Month"
set topsite(test_SECTION_6) "XXX-0DAY"
set topsite(test_SECTION_6_TODAY) "XXX-0DAY-today"
set topsite(test_SECTION_7) "XXX-iMAGESETS"
set topsite(test_SECTION_7_TODAY) "XXX-iMAGESETS-today"

set topsite(test_SECTION_8) "ANiMES-FR"
set topsite(test_SECTION_8_TODAY) "ANiMES-FR"
set topsite(test_SECTION_9) "APPS"
set topsite(test_SECTION_9_TODAY) "APPS"
set topsite(test_SECTION_10) "BLURAY"
set topsite(test_SECTION_10_TODAY) "BLURAY"
set topsite(test_SECTION_11) "DVDR"
set topsite(test_SECTION_11_TODAY) "DVDR"
set topsite(test_SECTION_12) "DVDR-DE"
set topsite(test_SECTION_12_TODAY) "DVDR-DE"
set topsite(test_SECTION_13) "DVDR-ES"
set topsite(test_SECTION_13_TODAY) "DVDR-ES"
set topsite(test_SECTION_14) "DVDR-FR"
set topsite(test_SECTION_14_TODAY) "DVDR-FR"
set topsite(test_SECTION_15) "DVDR-NL"
set topsite(test_SECTION_15_TODAY) "DVDR-NL"
set topsite(test_SECTION_16) "DVDR-NORDiC"
set topsite(test_SECTION_16_TODAY) "DVDR-NORDiC"
set topsite(test_SECTION_17) "DVDR-iTA"
set topsite(test_SECTION_17_TODAY) "DVDR-iTA"
set topsite(test_SECTION_18) "GAMES"
set topsite(test_SECTION_18_TODAY) "GAMES"
set topsite(test_SECTION_19) "MBLURAY"
set topsite(test_SECTION_19_TODAY) "MBLURAY"
set topsite(test_SECTION_20) "MDVDR"
set topsite(test_SECTION_20_TODAY) "MDVDR"
set topsite(test_SECTION_21) "NDS"
set topsite(test_SECTION_21_TODAY) "NDS"
set topsite(test_SECTION_22) "PS3"
set topsite(test_SECTION_22_TODAY) "PS3"
set topsite(test_SECTION_23) "PSP"
set topsite(test_SECTION_23_TODAY) "PSP"
set topsite(test_SECTION_24) "TV-DVDR"
set topsite(test_SECTION_24_TODAY) "TV-DVDR"
set topsite(test_SECTION_25) "TV-HD"
set topsite(test_SECTION_25_TODAY) "TV-HD"
set topsite(test_SECTION_26) "TV-HD-DE"
set topsite(test_SECTION_26_TODAY) "TV-HD-DE"
set topsite(test_SECTION_27) "TV-HD-ES"
set topsite(test_SECTION_27_TODAY) "TV-HD-ES"
set topsite(test_SECTION_28) "TV-HD-FR"
set topsite(test_SECTION_28_TODAY) "TV-HD-FR"
set topsite(test_SECTION_29) "TV-HD-NL"
set topsite(test_SECTION_29_TODAY) "TV-HD-NL"
set topsite(test_SECTION_30) "TV-HD-NORDiC"
set topsite(test_SECTION_30_TODAY) "TV-HD-NORDiC"
set topsite(test_SECTION_31) "TV-HD-iTA"
set topsite(test_SECTION_31_TODAY) "TV-HD-iTA"
set topsite(test_SECTION_32) "TV-HDRiP"
set topsite(test_SECTION_32_TODAY) "TV-HDRiP"
set topsite(test_SECTION_33) "TV-SD"
set topsite(test_SECTION_33_TODAY) "TV-SD"
set topsite(test_SECTION_34) "TV-SD-DE"
set topsite(test_SECTION_34_TODAY) "TV-SD-DE"
set topsite(test_SECTION_35) "TV-SD-ES"
set topsite(test_SECTION_35_TODAY) "TV-SD-ES"
set topsite(test_SECTION_36) "TV-SD-FR"
set topsite(test_SECTION_36_TODAY) "TV-SD-FR"
set topsite(test_SECTION_37) "TV-SD-NL"
set topsite(test_SECTION_37_TODAY) "TV-SD-NL"
set topsite(test_SECTION_38) "TV-SD-NORDiC"
set topsite(test_SECTION_38_TODAY) "TV-SD-NORDiC"
set topsite(test_SECTION_39) "TV-SD-iTA"
set topsite(test_SECTION_39_TODAY) "TV-SD-iTA"
set topsite(test_SECTION_40) "TV-SDRiP"
set topsite(test_SECTION_40_TODAY) "TV-SDRiP"
set topsite(test_SECTION_41) "Wii"
set topsite(test_SECTION_41_TODAY) "Wii"
set topsite(test_SECTION_42) "X264"
set topsite(test_SECTION_42_TODAY) "X264"
set topsite(test_SECTION_43) "X264-DE"
set topsite(test_SECTION_43_TODAY) "X264-DE"
set topsite(test_SECTION_44) "X264-FR"
set topsite(test_SECTION_44_TODAY) "X264-FR"
set topsite(test_SECTION_45) "X264-NL"
set topsite(test_SECTION_45_TODAY) "X264-NL"
set topsite(test_SECTION_46) "X264-NORDiC"
set topsite(test_SECTION_46_TODAY) "X264-NORDiC"
set topsite(test_SECTION_47) "X264-iTA"
set topsite(test_SECTION_47_TODAY) "X264-iTA"
set topsite(test_SECTION_48) "XBOX360"
set topsite(test_SECTION_48_TODAY) "XBOX360"
set topsite(test_SECTION_49) "XViD"
set topsite(test_SECTION_49_TODAY) "XViD"
set topsite(test_SECTION_50) "XViD-DE"
set topsite(test_SECTION_50_TODAY) "XViD-DE"
set topsite(test_SECTION_51) "XViD-FR"
set topsite(test_SECTION_51_TODAY) "XViD-FR"
set topsite(test_SECTION_52) "XViD-NL"
set topsite(test_SECTION_52_TODAY) "XViD-NL"
set topsite(test_SECTION_53) "XViD-NORDiC"
set topsite(test_SECTION_53_TODAY) "XViD-NORDiC"
set topsite(test_SECTION_54) "XViD-iTA"
set topsite(test_SECTION_54_TODAY) "XViD-iTA"
set topsite(test_SECTION_55) "XXX"
set topsite(test_SECTION_55_TODAY) "XXX"
set topsite(test_SECTION_56) "XXX-DE"
set topsite(test_SECTION_56_TODAY) "XXX-DE"
set topsite(test_SECTION_57) "XXX-DVDR"
set topsite(test_SECTION_57_TODAY) "XXX-DVDR"
set topsite(test_SECTION_58) "XXX-ES"
set topsite(test_SECTION_58_TODAY) "XXX-ES"
set topsite(test_SECTION_59) "XXX-FR"
set topsite(test_SECTION_59_TODAY) "XXX-FR"
set topsite(test_SECTION_60) "XXX-HD"
set topsite(test_SECTION_60_TODAY) "XXX-HD"
set topsite(test_SECTION_61) "XXX-iTA"
set topsite(test_SECTION_61_TODAY) "XXX-iTA"

namespace eval ::topclient {
    #Config bot per bot

```
#Si le botnet-nick à pas été renseigné dans le fichiers configuration, on recherche le nick IRC du bot :

if { [info exists ::botnet-nick] } { 
    if { ${::botnet-nick} == "" } { set ::who_name ${::nick}; } else { set ::who_name ${::botnet-nick}; }
} else { set ::who_name ${::nick}; }

switch -exact -- [string tolower $who_name] {
    shass  {
        # Si vous dsirer avoir un echo sur les channels des commandes
        # renseignez les channels, sinon mettez "" :
        set top_config(chan_debug) "rlzNET"
        set top_config(chan_addpre) "rlzNET"
        set top_config(chan_newdir) "rlzNET"
        set top_config(chan_addinfo) "rlzNET"
        set top_config(chan_addginfo) "rlzNET"
        set top_config(chan_sitepre) "rlzNET"
        set top_config(chan_mp3info) "rlzNET"
        set top_config(chan_fileinfo) "rlzNET"
        set top_config(chan_addnfo) "rlzNET"
        set top_config(chan_addm3u) "rlzNET"
        set top_config(chan_style) "rlzNET"
        set top_config(chan_addjpg) "rlzNET"
        set top_config(chan_addcue) "rlzNET"
        set top_config(chan_addsfv) "rlzNET"
        set top_config(chan_addcover) "rlzNET"
        set top_config(chan_addvideoinfo) "rlzNET"
        set top_config(chan_addmediainfo) "rlzNET"
        set top_config(chan_addurl) "rlzNET"
        set top_config(chan_req) "rlzNET"

        ### Configuration MySQL
        set sql_config(Host) "127.0.0.1"
        set sql_config(Port) ""
        set sql_config(User) "root"
        set sql_config(Pass) "root"
        set sql_config(DBName) "topsite_pre"

        # Si vous utilisez un botnet (plusieurs eggdrop relier entre eux)
        # Renseign le le nom du bot link qui devra recevoir toutes les commandes
        #
        ##Entrer le bot ou les commandes seront envoyers  :
                    set top_config(bot_dest) "all"
        # top_config(debug_ppl) Permet d'activé ou désactiver les annonces dans le ppl de votre EGG
        # Mettez 1 pour activer et 0 pour désactiver
        set top_config(debug_ppl) "1"

        #Skip list for dirname :
        set skipdirname "*-30CD* *Isanaki* *-G2K *-G0LDz *insecure* *bustme* *crapsite* *KiMSUFi* *SCENECLEAN* *NUKED* TEST* req-* req* archive* backup* affil* request* *P2P* *XXX-PAYSiTE*"

        #Skip list for section :
        set skipsection "*NUKED* req-* req* backup* affil* request* filled* *P2P* _STAFF _PRE SCENE-NEWS"
```

####set skipsection "_NUKED_ req-\* req\* backup\* affil\* filled\* _P2P_ _ARCHIVE _STAFF _PRE SCENE-NEWS"

```
        #Skip list for files :
        set skipfile "*.diz *.confict *.imdb *.date *.bad *.message *-offline *.racestats *-HORS-LIGNE *sfvdb* *(1)* *(2)* *(3)* *(4)* *(5)* *(6)* *(7)*"
    }
    #default {
        #die "\n\n\ncouldn't find my botnick ${nick} in configuration of Topclient\n\n\n"
    #}
}
```

}
package require http
package require tls
#package require crc32
#package require md5

#####################################
#

# top_config(lftp) contient le chemin complet lftp.

# lftp permet de ce connecté aux differents serveurs FTP

# Il doit tre imprativement installer.

# Renseigné sont chemmin :

set top_config(lftp) "/usr/bin/lftp";

#####################################
#

# Le package CRC est contenue dans apt-get install tcllib

# Si vous desirez indiquez vous meme le chemin de CRC32.tcl

# Renseigné sont chemmin :

#####################################
#

# Le package HTTP est contenue dans apt-get install tcllib

# Si vous desirez indiquez vous meme le chemin de HTTP.tcl

# Renseigné sont chemmin :

###set tcl_package(http) "/usr/share/tcltk/tcl8.4/http2.7.5/http.tcl";
#set tcl_package(http) "/usr/share/tcltk/tcl8.6/http1.0/http.tcl"
#####################################
#

# Le package tls est contenue dans apt-get install tcltls

# Si vous desirez indiquez vous meme le chemin de TLS.tcl

# Renseigné sont chemmin :

###set tcl_package(tls) "/usr/share/tcltk/tls1.50/tls.tcl";
set tcl_package(tls) "/usr/share/tcltk/tls1.6/tls.tcl"
#####################################
#

# top_config(ffmpeg) contient le chemin complet FFmpeg.

# FFmpeg permet de convertir les .avi en JPG pour addcover

# Il doit tre imprativement installer.

# Renseigné sont chemmin :

set top_config(ffmpeg) "";

#####################################
#

# top_config(www) contient le chemin complet au rpetoire

# www qui contiendra les differents fichiers qui seront

# accesible par HTTP. Cela permet de partag les NFO's, etc

# Ne doit pas ce terminer par /

#

# Entrer le chemin du repertoire :

set top_config(www) "/var/www/html/www/";

#####################################
#

# top_config(www_dns) contient l'adresse url (sans http://)

# de votre site web. Cela permet de partag les NFO's, etc

# Vous pouvez mettre l'IP ou un DNS, le port est facul

##Entrer le DNS du host apache (+ port) :
set top_config(www_dns) "";

#####################################
#

# top_config(www_path) est le chemin de votre repetoire top_config(www) en HTTP

# Permet acumul a top_config(www_dns) de partag les NFO's, etc

# Ne doit pas ce terminer par / si c'est directement a la racine mettez ""

#

# Entrer me chemin pour l'url :

set top_config(www_path) "/www";

#
#################################

# Global Variable

#################################
##

#####################################

# Informations :

# Vous avez deux solutions pour faire fonctionné ce TCL correctement :

#

# 1) Mettre le Eggdrop sur un channel, et ensuite sur ce channel

# lancé les commandes :

#

# !topcomplete <top_name> <release_name> <release_section> [release_file] [release_size]

# !topnew <top_name> <release_name> <release_section>

# !toppre <top_name> <release_name> <release_section> [release_file] [release_size]

#

# 2) Mettre le eggdrop sur tout les topsites et configurer pour

# que ce TCL ce lance pour chaque commandes :

#

# proc_topcomplete $nick $uhost $hand $chan "<top_name> <release_name> <release_section> [release_file] [release_size]"

# proc_topnew $nick $uhost $hand $chan "<top_name> <release_name> <release_section>"

# proc_toppre $nick $uhost $hand $chan "<top_name> <release_name> <release_section> [release_file] [release_size]"

#

# Toutes les données entre <> sont obligatoire, et ceux entre [] sont optionnels laissez vide ou remplacé par un tiret -

#
#####################################
##Site planet
bind PUBM -|- \* proc_annonce_top
#####################################

# proc_annonce_top

#####################################
proc proc_annonce_top { nick uhost hand chan arg } {

```
###### INIT - BEGIN ######
set arg [string map {"" ""} [stripcodes bcu $arg]]
###### INIT - END ######
```

# SITE test

```
    set site_name "test";
    #if { $nick != "***" } { return 0; }
    #Pre affils annonce..
    if { [string match "*pre*" [string tolower [lindex $arg 0]]] && [string match "*pre!*" [string tolower [lindex $arg 8]]] && [string match "*has*" [string tolower [lindex $arg 10]]] } {
            set release_name [lindex $arg 9]
            set release_section [lindex $arg 2]
            set release_section [string range $release_section 1 end-1]
            set release_file "-";
            set release_size "-";
            if { $::topclient::top_config(chan_debug) != "" } { putfast "privmsg $::topclient::top_config(chan_debug) :\0034$site_name\003 -> (\00310PRE\003):\0037 $release_name $release_section $release_file $release_size"; }
            proc_toppre $nick $uhost $hand $chan "$site_name $release_name $release_section $release_file $release_size";
            return 0;
    }

    #New annonce..
    if { [string match "*new*" [string tolower [lindex $arg 0]]] && [string match "*by*" [string tolower [lindex $arg 4]]] } {
            set release_name [lindex $arg 3]
            set release_section [lindex $arg 2]
            set release_section [string range $release_section 1 end-1]
```

# set release_section [string range $release_section 0 end-1]

```
            if  {$::topclient::top_config(chan_debug) != "" } { putfast "privmsg $::topclient::top_config(chan_debug) :\0034$site_name\003 -> (\00310NEW\003):\0037 $release_name $release_section"; }
            proc_topnew $nick $uhost $hand $chan "$site_name $release_name $release_section";
            return 0;
    }


    #Complete annonce..
    if { [string match "*done*" [string tolower [lindex $arg 0]]]} {
            set release_name [lindex $arg 2]
            set release_section [lindex $arg 1]
            set release_section [string range $release_section 1 end-1]
```

# set release_section [string range $release_section 0 end-1]

```
            set release_file "-";
            set release_size "-";
            if { $::topclient::top_config(chan_debug) != "" } { putfast "privmsg $::topclient::top_config(chan_debug) :\0034$site_name\003 -> (\00310COMPLETE\003):\0037 $release_name $release_section $release_file $release_size"; }
            proc_topcomplete $nick $uhost $hand $chan "$site_name $release_name $release_section $release_file $release_size";
            return 0;

    }
```

}

proc putfast {arg} {
append arg "\n"
putdccraw 0 [string length $arg] $arg
}

**Comment by dupe** [comment]
humm  
no good set top_config(chan_debug) "rlzNET"
good set is set top_config(chan_debug) "#rlzNET"  
set set top_config(bot_dest) "all"  
name bot eggdrop irc login 

proc proc_annonce_top { nick uhost hand chan arg } {###### INIT - BEGIN ######
set arg [string map {"�" ""} [stripcodes bcu $arg]]
###### INIT - END ######

and no good set set name bot  name  topsite annoncing irc  and set trigger bot 
line 318 and line 360 

Date: Sat, 30 May 2015 00:45:44 -0700

**Comment by dupe** [comment]
and 
#if { $nick != "***" } { return 0; }
to if { $nick != "blabla" } { return 0; }

Date: Sat, 30 May 2015 00:45:44 -0700

**Comment by dupe** [comment]
humm  

no good set top_config(chan_debug) "rlzNET"

good set is set top_config(chan_debug) "#rlzNET"  

set set top_config(bot_dest) "all"  

name bot eggdrop irc login 

proc proc_annonce_top { nick uhost hand chan arg } {

###### INIT - BEGIN

set arg [string map {"�" ""} [stripcodes bcu $arg]]

###### INIT - END

and no good set 
set name bot  name  topsite annoncing irc  and set trigger bot 

line 318 and line 360 

and 

#if { $nick != "***" } { return 0; }

to 
if { $nick != "blabla" } { return 0; }

**Comment by dupe** [comment]
and 
no good set
#package nécessitent crc32 
#package nécessitent md5

package nécessitent crc32 
package nécessitent md5

**Comment by dupe** [comment]
do not change the line or the script will not work

**Comment by scriptzteam** [comment]
wait going test again :)

**Comment by dupe** [comment]
those script running your bot eggdrop

which must be connected on the IRC chan

and configures the bot top site that advertises on irc

**Comment by scriptzteam** [comment]
http://pastebin.com/XAg1qJq5 --- just got again "couldn't find my botnick blabla in configuration of Topclient"

[10:11] --- Loading eggdrop v1.6.19+SSL (Sat May 30 2015)
[10:11] Module loaded: dns
[10:11] Module loaded: channels
[10:11] Module loaded: server
[10:11] Module loaded: ctcp
[10:11] Module loaded: irc
[10:11] Module loaded: notes            (with lang support)
[10:11] Module loaded: console          (with lang support)
[10:11] Module loaded: blowfish
[10:11] Listening at telnet port 3333 (all).
[10:11] Module loaded: uptime
[10:11] *

couldn't find my botnick blabla in configuration of Topclient

**Comment by dupe** [comment]
lol couldn't find my botnick blabla in configuration of Topclient

set your name bot eggdrop

**Comment by dupe** [comment]
put the name of your bot that you had given him in the eggdrop.conf

**Comment by dupe** [comment]
and 

set top_config(chan_debug) "#rlzNET"
                        set top_config(chan_addpre) "#rlzNET"
                        set top_config(chan_newdir) "#rlzNET"
                        set top_config(chan_addinfo) "#rlzNET"
                        set top_config(chan_addginfo) "#rlzNET"
                        set top_config(chan_sitepre) "#rlzNET"
                        set top_config(chan_mp3info) "#rlzNET"
                        set top_config(chan_fileinfo) "#rlzNET"
                        set top_config(chan_addnfo) "#rlzNET"
                        set top_config(chan_addm3u) "#rlzNET"
                        set top_config(chan_style) "#rlzNET"
                        set top_config(chan_addjpg) "#rlzNET"
                        set top_config(chan_addcue) "#rlzNET"
                        set top_config(chan_addsfv) "#rlzNET"
                        set top_config(chan_addcover) "#rlzNET"
                        set top_config(chan_addvideoinfo) "#rlzNET"
            set top_config(chan_addmediainfo) "#rlzNET"
                        set top_config(chan_addurl) "#rlzNET"
                        set top_config(chan_req) "#rlzNET"

sur bot topsite annoncing to chan set ?

**Comment by scriptzteam** [comment]
topsite conf
 set top_config(bot_dest) "blabla"

eggdrop.conf

##### Settings:

# Set the nick the bot uses on IRC, and on the botnet

# unless you specify a separate botnet-nick, here.

set nick "blabla"

# Set the alternative nick which the bot uses on IRC if the nick specified by 'set nick'

# is unavailable. All '?' characters will be replaced by random numbers.

set altnick "blabla"

# Set here what should be displayed in the real-name field for the bot on IRC.

set realname "/msg blabla hello"

**Comment by dupe** [comment]
your name bot eggdrop is ?

**Comment by scriptzteam** [comment]
eggdrop name bot is blabla

**Comment by dupe** [comment]
use botnet ?

**Comment by dupe** [comment]
restarting eggdrop

**Comment by dupe** [comment]
# SITE ****

```
    set site_name "test";
    if { $nick != "blabla" } { return 0; }
```

no set name bot topsite no your bot egddrop
